sibiraj-s/ngx-editor

- src/app/ngx-editor/ngx-editor.component.html
- src/app/ngx-editor/ngx-editor.component.ts
- src/app/ngx-editor/ngx-editor.defaults.ts
set `width` and `minWidth` to editor. 
```
width: auto
minWidth: 0
```
> add width property to editor

- .angular-cli.json
- e2e/app.e2e-spec.ts
- e2e/app.po.ts
- package.json
- protractor.conf.js
> fix e2e tests

- .travis.yml
* update to node.js 8.9.1
* update ci browser
> update nodejs to 8.9.1

- package.json
> chore: update scripts

- src/app/ngx-editor/ngx-editor.component.ts
Some events have been handled internally, there were no public api to handle this event from parent component. i have just emit the blur and focus event which handled for disable the buttons on toolbar. now we can receive this from parent.
> Added to Event Emitter to receive 'blur' and 'focus' events from parent component which holds the Editor.

- .travis.yml
- src/app/app.component.html
* open current release link in new tab
> open current release link in new tab

- .travis.yml
- package-lock.json
- src/app/ngx-editor/ngx-editor.component.ts
- yarn.lock
* update Travis to run in trusty environments
* update License for current year
* update dependencies
> chore: repository maintenance

- .gitignore
- package-lock.json
- package.json
- src/app/ngx-editor/ngx-editor-toolbar/ngx-editor-toolbar.component.scss
- src/app/ngx-editor/ngx-editor.component.html
- src/app/ngx-editor/ngx-editor.component.ts
* closes #43 
* closes #44 
* closes #45
> ngx-editor: release v3.3.0-rc.3

- .travis.yml
- ng-package.json
- package-lock.json
- package.json
- public_api.ts
- src/public_api.ts
- tsconfig.json
* update ng-packagr to stable verison
> update ng-packagr to stable version

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
add ISSUE TEMPLATE and PR Template
> add ISSUE TEMPLATE and PR Template

- docs/injectables/CommandExecutorService.html
- package-lock.json
- package.json
- src/app/ngx-editor/common/services/command-executor.service.ts
closes #61
Link is being inserted twice due to duplicate code.
closes #61
> fix: insert link once

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.service.ts
- src/app/ngx-editor/common/ngx-editor.defaults.ts
- src/app/ngx-editor/ngx-editor.component.ts
_describe the changes that you are making_
_for features, please describe how to use the new feature_
> [Fix]: Codemirror`s HTML mode colouring

- package-lock.json
- package.json
> release: ngx-editor v3.3.0-rc.11

- README.md
Remove codemirror from Readme.md
> [Docs]: Removed codemirror from readme

- package-lock.json
- package.json
> release: ngx-editor v3.3.0-rc.14

- package-lock.json
- package.json
- src/lib/ngx-editor.component.scss
- src/lib/plugins/menu/getMenu.ts
- src/ng-package.json
- src/package.json
> Remove unwanted dependencies

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.1

- src/lib/ngx-editor.component.ts
- src/lib/utils/computeOptions.ts
Don't override custom config with default config
Closes #207
> Don't override custom config with default config

- src/lib/ngx-editor.component.html
Remove empty dom wrapper
Closes #131
> Remove empty DOM wrapper

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.3

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.4

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.5

- README.md
- wiki/content/examples.md
- wiki/content/ng-model.md
> Docs: Update Examples

- src/lib/ngx-editor.component.scss
> Fix styles

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.6

- README.md
- demo/src/app/app.component.ts
- demo/src/app/doc.ts
> Update demo and readme

- demo/src/app/app.component.html
- demo/src/app/app.component.scss
- demo/src/app/plugins/menu/codemirror.ts
- src/lib/ngx-editor.component.ts
Handle null value input correctly
> Bug Fix: Handle null value input correctly

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.7

- CHANGELOG.md
- README.md
- src/package.json
> Release v5.0.0 alpha.8

- src/lib/ngx-editor.component.ts
- wiki/content/reactive-forms.md
- wiki/summary.json
Fix reactive forms
Closes #234
> Fix reactive forms

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.9

- .github/workflows/gh-pages.yml
> ci: update gh-pages.yml

- src/app/ngx-editor/ngx-editor-toolbar/ngx-editor-toolbar.component.html
Allows that the `Insert Video Form` `width` and `height` values to be more than one numeric character. 
fixes #263: change the validation form
I think this PR should be merged for v4.1.1 instead of going to master.
> fix: 263 change insert video validation form

- CHANGELOG.md
- src/package.json
> Release V5.0.0 alpha.11

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.12

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.13

- .github/workflows/tests.yml
- README.md
- package.json
- src/package.json
> Support angular 9

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.14

- CHANGELOG.md
- README.md
- docs/README.md
- src/package.json
> Release v5.0.0 alpha.15

- README.md
- demo/src/app/app.component.html
- demo/src/app/app.component.spec.ts
- demo/src/app/app.component.ts
- demo/src/app/app.module.ts
- docs/reactive-forms.md
- src/lib/Validators.ts
- src/lib/editor.component.ts
- src/lib/schema.ts
- src/lib/validators.ts
- src/public_api.ts
- fixed an issue with touched event not registered when using reactive forms
- added required validators
closes #125
> Reactive forms

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.16

- README.md
- demo/src/app/plugins/index.ts
- docs/README.md
- docs/configuration.md
- docs/plugins.md
- src/lib/editor.component.ts
- src/lib/modules/menu/menu.component.scss
- src/plugins/placeholder.ts
- src/plugins/public_api.ts
- fix menu icons shrink on resize
- fix image plugin not exported with correct name
- allow placeholder to be set via editor component
Fixed export `imagePlugin` to `image`
closes #220
> Enhancements

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.17

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.18

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.19

- CHANGELOG.md
- src/package.json
> Release v5.0.0-alpha.20

- CHANGELOG.md
- src/package.json
> Release v5.0.0-beta.1

- .github/PULL_REQUEST_TEMPLATE.md
- demo/src/app/app.module.ts
- demo/src/app/plugins/index.ts
- docs/full-featured-editor.md
- docs/menu.md
- package.json
- src/commands/applyMark.ts
- src/lib/commands/TextColor.ts
- src/lib/editor.component.html
- src/lib/editor.component.ts
- src/lib/editor.service.ts
- src/lib/html.ts
- src/lib/modules/menu/color-picker/color-picker.component.html
- src/lib/modules/menu/color-picker/color-picker.component.ts
- src/lib/schema/marks.ts
- src/lib/schema/nodes.ts
- src/lib/types.ts
- src/lib/utils/toStyleString.ts
- custom color presets
- prevent crash while selection
- fix prevent color selection on right click
- fix autoscroll while applying colors without selection.
> Custom color presets + Bug Fixes

- CHANGELOG.md
- src/package.json
> Release v5.0.0-beta.2

- docs/menu.md
Added some details for Custom Menu. There wasn't anything missing from the existing documentation but I've added some explicit details.
> Added some details to custom menu documentation

- docs/_sidebar.md
- docs/mentions.md
I add documentation for prosemirror-mentions plugin support
> docs: add mentions documentation

- projects/ngx-editor/src/lib/modules/menu/image/image.component.ts
- projects/ngx-editor/src/lib/modules/menu/link/link.component.ts
I cange url patterns.
More info: https://github.com/sibiraj-s/ngx-editor/issues/343
Fix https://github.com/sibiraj-s/ngx-editor/issues/343.
> Fix: Support query string in URL

- docs/editor.md
- projects/demo/src/app/app.component.ts
- projects/ngx-editor/src/lib/Editor.ts
Refer to discussion: https://github.com/sibiraj-s/ngx-editor/discussions/365
> feat: support attributes to forward to ProseMirror editor

- package-lock.json
- package.json
- projects/ngx-editor/src/lib/defaultPlugins.ts
- projects/ngx-editor/src/public_api.ts
- scripts/install-husky.sh
In order to submit this PR, I had to add support for building on Windows too using `run-script-os`.
TODO: is a docs update needed here?
Fixes #373
> fix: export getDefaultPlugins and getKeyboardShortcuts methods

- docs/editor.md
> docs: typo (Editor.md)

- docs/reactive-forms.md
fixed the declaration of ngOnDestroy
> docs: typo on ngOnDestroy

- projects/ngx-editor/src/public_api.ts
Add NgxEditorService to public_api. This will allow you to inherit custom translation services in your own Angular applications.
> Add NgxEditorService to public_api.ts (Public API Surface of ngx-editor)

- docs/src/content/docs/en/migrations/migration.md
> docs: Fix typo in migration.md

- angular.json
- package-lock.json
- package.json
- projects/ngx-editor/package.json
Updated project to Angular version 17.
Updated project to Angular version 17.
Closes #509
> feat: upgrade to angular v17
